### ISSUE TITLE
Support more jpg variation format | 支持更多jpg格式的变体

### ISSUE THREAD

**Issue by HowcanoeWang** [AShujiao/vscode-background-cover#107]
e.g. twitter downloaded `*.jfif` format (can change extention to `*.jpg` without any problem)

> 如推特下载的`*.jfif`格式，可以直接通过修改文件后缀来变成`*.jpg`

![image](https://user-images.githubusercontent.com/19968935/230719248-9156a135-ab62-49c8-8584-522a94ce665b.png)

These `*.jfif` not show in the extention

> 插件中不显示`*.jfif`文件

**Comment by AShujiao** [comment]
这种非 主流的图片格式没法全部都适配，既然你提了这个，那等后期版本更新时带上这个格式。
