### ISSUE TITLE
vscode连远程服务器不显示背景图

### ISSUE THREAD

**Issue by liuxingbo12138** [AShujiao/vscode-background-cover#109]
在本机选择背景图能正常显示，ssh连服务器后就不显示了，把图片上传到服务器上然后再选择也不显示

**Comment by BitCalSaul** [comment]
遇到相似的问题了, 作者可以开发一下ssh背景功能吗, 会追加很多杯咖啡的~

**Comment by AShujiao** [comment]
话说这种情况有好多次反馈了，但我还真没复现出来。理论上vscode是在你本地环境安装的背景也写入到文件里了，就算连接shh也不会重置图片才对。
