### ISSUE TITLE
ubuntu 22.04 vscode  未捕获的错误(1)

### ISSUE THREAD

**Issue by watchgou** [AShujiao/vscode-background-cover#113]
EROFS: read-only file system, open '/snap/code/137/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css'

**Comment by AShujiao** [comment]
感谢反馈，这种还是权限的问题。如果用不了给下对应的权限或者参考置顶的issue

**Comment by watchgou** [comment]
感谢回复。

**Comment by AShujiao** [comment]
最新版已处理该问题
