### ISSUE TITLE
English language is not working 

### ISSUE THREAD

**Issue by HappyBravo** [AShujiao/vscode-background-cover#124]
<img width="416" alt="Screenshot 2024-05-28 163647" src="https://github.com/AShujiao/vscode-background-cover/assets/83241650/7bacc0a7-71ab-4290-9087-406c72f6c0b7">

when I click on English, it looks like it refreshes. but the language is still not English.
Also, if possible add English "subtitles" 😬. as it is in the repo's README

**Comment by AShujiao** [comment]
First of all, I tried switching languages ​​and it was normal. You can try it a few more times. But I'm sorry that I can't support both Chinese and English like Reamde. This workload is a bit large. I will create another theme to introduce the usage and precautions in English.
In addition, this is a website hosted in mainland China. There may be some compatibility issues when integrated into vscode. You can try to access the address directly: https://vs.20988.xyz/, (I'm not sure if it can be opened normally abroad).
