### ISSUE TITLE
Update 2.5.1 disabled the background wallpaper in macos sonama 14.5 (23F79)

### ISSUE THREAD

**Issue by Akashdip-N** [AShujiao/vscode-background-cover#125]
With the recent update, the extension cannot verify the original password with the one entered in the prompt section.
Though both of them are the same, it still shows the error message, "Password is incorrect" but everything works perfectly with the older version.

**Comment by AShujiao** [comment]
新版中并没有变动这块功能，建议你参考 #87  ，看是否能解决问题

**Comment by Akashdip-N** [comment]
问题已解决

The issue has been resolved.
