### ISSUE TITLE
mac下选择背景后不生效

### ISSUE THREAD

**Issue by GeeKaven** [AShujiao/vscode-background-cover#126]
vscode版本：1.89.1
插件版本：2.5.1

vscode已经是完全磁盘访问权限了，修改背景后不生效，也提示code损坏了，应该是修改了

  #87 这个里面我的vscode用brew安装的一直都是在启动台里的

**Comment by 1491085620** [comment]
vscode版本：1.90.0
插件版本：2.5.1
也不生效，已经提示code损坏

**Comment by AShujiao** [comment]
已处理，请更新到2.5.2尝试一下是否解决问题

**Comment by GeeKaven** [comment]
更新后好像解决了

**Comment by AShujiao** [comment]
> 更新后好像解决了

好的，再有问题欢迎反馈，其实是解决了一个使用在线后再使用本地图片的bug。使用在线图片后再改为本地图片会导致将本地图片识别为在线图片，所以不展示。

**Comment by AShujiao** [comment]
请尝试2.53

**Comment by GeeKaven** [comment]
2.53更新后解决问题，谢谢
