### ISSUE TITLE
Mac升级插件版本到2.5.1后背景图片完全不显示

### ISSUE THREAD

**Issue by HarryXueTJU** [AShujiao/vscode-background-cover#127]
VS Code: 1.90.1
Background Cover: 2.5.1
升级后插件未出现报错，但背景图片消失，任何配置都不能使图片出现，插件重新安装也还是同样现象。

**Comment by kyrosle** [comment]
我也遇到了, 而且修改图片的不透明度, 不会显示图片而且会导致整个界面灰蒙蒙的

**Comment by PCKxin** [comment]
大概是vscode版本的问题,背景变量应该是被修改了
昨天先升级的插件,后面午饭时间升级了一下code,升级完插件就挂了

**Comment by AShujiao** [comment]
。。能提供下远程环境不。。

**Comment by kyrosle** [comment]
> 。。能提供下远程环境不。。

是其他平台没有出现这个问题吗

**Comment by AShujiao** [comment]
> > 。。能提供下远程环境不。。
> 
> 是其他平台没有出现这个问题吗

是的，目前win正常

**Comment by Akashdip-N** [comment]
对于那些在 Mac 上遇到问题的人，最好将此扩展的先前版本 2.5.1 安装到您的 vscode 上，这就是我在过去 2 周中使用它的方式。

**Comment by ciaoyizhen** [comment]
@Akashdip-N 非常有用  版本降了就行了!!!

**Comment by PCKxin** [comment]
降级到2.4.0 可以正常使用了

**Comment by Akashdip-N** [comment]
@ciaoyizhen 不幸的是，到目前为止，这是最适合 Mac 操作系统的！ 😅

**Comment by AShujiao** [comment]
抱歉，既然低版本可以用那还是插件的问题，我会尽快修复

**Comment by AShujiao** [comment]
![微信图片_20240611164547](https://github.com/AShujiao/vscode-background-cover/assets/14969576/88e7d399-e450-4819-b362-1dd4b45ece9c)
我这边找了个air试了下，用网络图片和本地图片都正常。但我这个应该是1.90

**Comment by Akashdip-N** [comment]
谢谢您，正在等待扩展修复:)

**Comment by kyrosle** [comment]
![image](https://github.com/AShujiao/vscode-background-cover/assets/74538854/9f8c944e-22d3-4698-8984-c487071b4485)
1.90.1好像又不work了

**Comment by HarryXueTJU** [comment]
目前的情况是降级到2.4.0就可以work 期待高版本尽早修复 感谢作者大大

**Comment by AShujiao** [comment]
..你们来个人提供下环境吧，我现在用了air试的正常，没法复现

**Comment by saiuya** [comment]
vscode: 1.90.1 (Universal) and plugin v2.5.1 are not work together !

**Comment by AShujiao** [comment]
已处理，请更新到2.5.2尝试一下是否解决问题

**Comment by Akashdip-N** [comment]
抱歉，问题仍然存在！

**Comment by AShujiao** [comment]
> 很遗憾,无法使用 插件版本2.5.2 vscode 1.90.2



> 抱歉，问题仍然存在！

现在的问题是本地图片和在线https图片都不能用吗？麻烦两种情况都试下

**Comment by PCKxin** [comment]
> > 很遗憾，无法使用插件版本2.5.2 vscode 1.90.2
> 
> > 抱歉，问题仍然存在！
> 
> 现在的问题是本地图片和在线https图片都不能用？

在线的目前可以用 - 2024/6/25 AM10:31

**Comment by AShujiao** [comment]
请尝试2.53

**Comment by PCKxin** [comment]
> 请尝试2.53

可以了, 感谢作者大大

**Comment by Akashdip-N** [comment]
@AShujiao 
该问题现已修复！

谢谢 ：）
