### ISSUE TITLE
Version > 2.4.0无法显示图片 / Version > 2.4.0 doesn't work

### ISSUE THREAD

**Issue by HenryZNNUE** [AShujiao/vscode-background-cover#128]
系统： Windows 11 23H2, Visual Studio Code 1.90.2
如果安装版本大于2.4.0，则无法显示背景图片

Operating System: Windows 11 23H2, Visual Studio Code 1.90.2
The extension will fail to display the selected backgroung image if the installed version is higher than 2.4.0

**Comment by AShujiao** [comment]
已处理，请更新到2.5.2尝试一下是否解决问题

**Comment by HenryZNNUE** [comment]
目前更新到2.5.2后手动选择图片并选择重启生效后依旧不能够正常显示背景图片，原来选择的背景图片会被替换为vscode的默认背景

**Comment by HenryZNNUE** [comment]
对，就是没有背景

**Comment by AShujiao** [comment]
..复现不了，要不你加下微信我远程看下

**Comment by fruitsdrink** [comment]
2.5 以后不能显示背景图片

**Comment by AShujiao** [comment]
请尝试2.53
