### ISSUE TITLE
Stop adding webview leading to spam sites

### ISSUE THREAD

**Issue by Paper-Folding** [AShujiao/vscode-background-cover#130]
We need a pure extension that does its job, not redundant/useless functionality which makes the extension bloatware.

**Comment by AShujiao** [comment]
Sorry I don't quite understand what you mean. The webview added after 2.5.0 is an online gallery, but it may only be accessible to users in mainland China. It is not a spam website.

**Comment by Paper-Folding** [comment]
Fine, I guess the functionality is kind of ridiculous when I stumble across the panel in vscode. It reminds me of a few bloatware I have used before. Since your extension is open source, I just removed the webview and published my own version. Apologize for bothering.
