### ISSUE TITLE
升级后,Win10系统下图片无法显示

### ISSUE THREAD

**Issue by XIAN-MASHI** [AShujiao/vscode-background-cover#133]
兄弟们,大佬们,自从那天我升级了插件后,图片就再也不显示了,试过改写插件的js文件,连重装code都试过了,也还是没用,没有我的老婆做背景,这代码是一丢丢都写不下去啊,救救我吧.对了,我在虚拟机deepin系统下也不能显示,但是在虚拟机win10下又可以显示.好神奇,明明我的实机系统也是win10.

**Comment by AShujiao** [comment]
啊，win系统一般不显示问题基本都是没有以管理员身份运行导致的。其它的还真没遇到过。
