### ISSUE TITLE
选择完图片并且立即加载生效，vscode刷新了但是背景未修改

### ISSUE THREAD

**Issue by wwwuxy** [AShujiao/vscode-background-cover#134]
我用的ubuntu22.04LST，vscode版本为1.19.0，也给了-R权限，请问怎么解决呢？

**Comment by AShujiao** [comment]
未修改时指之前有图片没有更换成功，还是一直就没背景图

**Comment by wwwuxy** [comment]
> 未修改时指之前有图片没有更换成功，还是一直就没背景图

一直都没有

**Comment by AShujiao** [comment]
试下用https的图片是否生效

**Comment by wwwuxy** [comment]
不太理解如何操作，在选择图片时会让我在本地文件夹内选择，您的意思是从网上下载图片到本地，在选取该图片吗

**Comment by AShujiao** [comment]
不是，这个有个输入https链接的方式
![image](https://github.com/user-attachments/assets/6d0b5a32-d049-4c4f-bf1d-a863d11a930b)

**Comment by wwwuxy** [comment]
好的，尝试了一下，还是不行诶

**Comment by AShujiao** [comment]
https都不行，那应该还是权限的问题。你参考下 #28 这里的处理方式，里面有个源文件你设置背景后打开源文件有没有追加相关css样式，文件路径是：/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.css，如果文件最后没有任何扩展追加的样式就是没权限

**Comment by wwwuxy** [comment]
![选区_026](https://github.com/user-attachments/assets/6500f475-4f84-4270-9e87-b227e594541c)
我的权限是这样，但是还是不行诶
