### ISSUE TITLE
In linux can load online pic but can't load local one. 在linux下可加载在线图片但无法加载本地图片

### ISSUE THREAD

**Issue by txjdsk** [AShujiao/vscode-background-cover#135]
![image](https://github.com/user-attachments/assets/d6cac48a-391c-4441-b7d5-f7bf47a29898)
加载本地图片时报错信息如图
![image](https://github.com/user-attachments/assets/7ae3d579-ce2c-42d5-b4e2-b7c17071bf46)
https模式则正常

**Comment by txjdsk** [comment]
![image](https://github.com/user-attachments/assets/0021ac33-4856-4180-a24f-33295f25f045)
找到解决办法了，把这里的改成
![image](https://github.com/user-attachments/assets/07bf509b-1395-4a64-a8fd-2495ed93499d)
删掉vscode-app后的一个斜杠即可
但是这样手动改总不是个事，作者大佬考虑修复一下？

**Comment by AShujiao** [comment]
好的，我会尽快修复，多谢提供解决方法

**Comment by AShujiao** [comment]
已在2.5.4版本修复该问题
