### ISSUE TITLE
可以用css给图片添加一层模糊blur效果

### ISSUE THREAD

**Issue by yebei199** [AShujiao/vscode-background-cover#137]
我记得css可以添加这样一层效果的, 最后效果很漂亮, 我之前写的浏览器插件就用了
![image](https://github.com/user-attachments/assets/a0c8012b-6442-4207-9af1-1ebcb9ff5063)

**Comment by AShujiao** [comment]
最近有比较忙，有时间我看下

**Comment by AShujiao** [comment]
release中已发布2.6.0体验一下模糊效果吧

**Comment by yebei199** [comment]
> release中已发布2.6.0体验一下模糊效果吧
好的喵
