### ISSUE TITLE
macOS下无法添加WebP格式的图片

### ISSUE THREAD

**Issue by TerakomariGandesblood** [AShujiao/vscode-background-cover#139]
RT

插件版本：2.5.3
VSCode版本：1.92.2

**Comment by TerakomariGandesblood** [comment]
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/c0f5a9e6-1b26-4928-97f5-e58c09715aaf">
灰色，无法选中

**Comment by AShujiao** [comment]
后期添加

**Comment by AShujiao** [comment]
这个确认了一下，是支持这个webp格式的，但你这个选择不了应该不是扩展的问题，可能是权限的原因。

**Comment by TerakomariGandesblood** [comment]
我把png和webp图片放在同一目录下，vscode对此目录有访问权限，两图片rwx相同
<img width="768" alt="image" src="https://github.com/user-attachments/assets/e4c7eef1-63f7-4530-9899-36cf98ff4986">
结果是png可以选中，但是webp无法选中
<img width="768" alt="image" src="https://github.com/user-attachments/assets/17ff3901-4b26-412d-bd19-d2cff0d0ce8d">
看起来不像是权限问题
@AShujiao

**Comment by AShujiao** [comment]
> 我把png和webp图片放在同一目录下，vscode对此目录有访问权限，两图片rwx相同 <img alt="image" width="768" src="https://private-user-images.githubusercontent.com/29801775/360225538-e4c7eef1-63f7-4530-9899-36cf98ff4986.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTQ5MDUsIm5iZiI6MTcyNDI5NDYwNSwicGF0aCI6Ii8yOTgwMTc3NS8zNjAyMjU1MzgtZTRjN2VlZjEtNjNmNy00NTMwLTk4OTktMzZjZjk4ZmY0OTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAyNDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MTQ2MDlkZDMxMmY1MDI4ZTE2MjI3MDc3MzYxZjg4OTkzMTUwYTYyOWEzZjFlYTRkZWU4YzhjYjc4OGFlN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ciequLgkrrN4y4MC6sY0o5BhAJEXF9lbzLdGuc01KTQ"> 结果是png可以选中，但是webp无法选中 <img alt="image" width="768" src="https://private-user-images.githubusercontent.com/29801775/360225631-17ff3901-4b26-412d-bd19-d2cff0d0ce8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTQ5MDUsIm5iZiI6MTcyNDI5NDYwNSwicGF0aCI6Ii8yOTgwMTc3NS8zNjAyMjU2MzEtMTdmZjM5MDEtNGIyNi00MTJkLWJkMTktZDJjZmYwZDBjZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAyNDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NmIyNzg1OTMzOWNlNDM0YzllODRkYmYyMWQ4ODU2YzM1MmE5ZDFlMTBiZDgyMWExNzFhN2JiZjJmNjIwZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XTkpR1N6aMLTCRpfa0jhTBzsOlMhL8_BOewn1GT_MdA"> 看起来不像是权限问题 @AShujiao

是我疏忽了，代码里有两处要定义格式的位置，只有一处改了。等下我重新发一下

**Comment by AShujiao** [comment]
修复了，不过由于今天刚发过版，要等下次发版带上这个了，你可以到release中下载插件，手动安装先用着。https://github.com/AShujiao/vscode-background-cover/releases/tag/2.5.4
