### ISSUE TITLE
求助，win11突然无法显示背景，是管理员身份运行

### ISSUE THREAD

**Issue by ability66** [AShujiao/vscode-background-cover#144]
如题，就重新打开了一下窗口，然后背景就全没了，即使重新选择图片也不显示，后续尝试在线图库，发现和选择本地图片一样报错
![image](https://github.com/user-attachments/assets/4e72fbb2-659f-4c5e-819b-131820751419)

**Comment by ability66** [comment]
回调版本，vs重装这些都尝试过，但是都无法解决，图片中的报错是尝试使用在线图库的图片报错，报错信息和选择本地图片一样

**Comment by Fantastair** [comment]
10月2号更新版本以后好像就不能用了，等作者更新吧

**Comment by Fantastair** [comment]
我回退版本到v1.9.3就可以了

**Comment by AShujiao** [comment]
抱歉假期没关注，刚看到，今天看下

**Comment by AShujiao** [comment]
已修复，请将扩展更新到2.5.5（不过我只验证了win系统），其它系统如果有问题请反馈！再次感谢大家对这个扩展的喜爱！
