### ISSUE TITLE
於 VSCodium 1.94.2 Release 24284 選取背景圖功能執行失敗，並且無任何錯誤訊息

### ISSUE THREAD

**Issue by Kayxue** [AShujiao/vscode-background-cover#147]
如影片所示，選完背景圖，就沒有下一步了，並且沒有任何錯誤訊息出現，並且重新啟動後背景圖也無任何改變
預期行為：選取完背景圖後會出現「是否立即重新啟動」
系統為 Mac OS Sequoia
https://github.com/user-attachments/assets/2ccbdefd-ad8c-4cd3-b0fd-4462bd7b32ad

**Comment by AShujiao** [comment]
扩展是最新的2.5.5版本吗?

**Comment by Kayxue** [comment]
> 你是第一次用这个扩展出现该问题，还是说升级vsc后出现的？

升級後出現的

**Comment by Kayxue** [comment]
> 扩展是最新的2.5.5版本吗?

感謝，升到 2.5.5 後好了
好像因為 VSCodium 使用不同的擴充庫，所以模組有更新 VSCodium 好像它自己是找不到的，剛剛一看才知道版本是 2.3.6，不知道多久沒更新了，感謝作者的幫助
