### ISSUE TITLE
求问

### ISSUE THREAD

**Issue by 2301762741** [AShujiao/vscode-background-cover#150]
作者大大，就是我想问下vscode更新改的javascript美化位置在哪个改怎么改，或者说有没有一种方法能根据代码位置的变量来动态获取这个值来动态修改后面再也不用手改了。
有个作者也是开发的个美化插件，太喜欢好用了但是作者它停止维护了，我想帮他接力继续开发维护下去，但是新手头疼都看到它那环境大概修改的位置了就是不知道怎么修改，后面自己花了很多时间自己结果环境也有问题弄不上有点绝望

**Comment by AShujiao** [comment]
大致实现方式就是改vsc底层的css、js文件，追加自己的代码上去，例如css的位置在vsc目录下的：/resources/app/out/vs/workbench/workbench.desktop.main.css  下，css的这种方式目录是不支持动态的修改，js的方式是可以实现的。

**Comment by 2301762741** [comment]
有点不解，就是我学习阶段的认为 css不应该有调用的此能生效吗，这样直接加自己的只改css就可以吗？？
目前在改《A-SOUL-live2d》希望能改对生效就行 ，看了下部分调用代码把原项目照作者改成这样感觉还是不行，不知道怎么改希望作者大大再指导下不？❤
![Uploading QQ截图20241112154436.png…]()
