### ISSUE TITLE
如何关闭背景模糊设置？

### ISSUE THREAD

**Issue by Goodnameisfordoggy** [AShujiao/vscode-background-cover#155]
我体验了一下背景模糊设置，但是我的背景图片不太适合启用此设置；我试图关闭该设置，即将模糊度设置为0，但是此时的背景与更新之前的背景还是有一定区别，我的字体在当前背景还是有些模糊；如何完全关闭该项设置？

**Comment by Goodnameisfordoggy** [comment]
后续我通过卸载重装插件重新设置图片，再降低0.2的图片不透明度，将背景调节到了与启用背景模糊之前类似的效果。背景模糊设置是否自动调节了图片透明度设置？之前图片不透明度设置的值忘记了Qwq

**Comment by AShujiao** [comment]
模糊设置为0就不会有其它模糊效果了。这次新版增加了一个新的css样式“css mix-blend-mode”但这个也不影响图片透明度。

**Comment by Goodnameisfordoggy** [comment]
> 模糊设置为0就不会有其它模糊效果了。这次新版增加了一个新的css样式“css mix-blend-mode”但这个也不影响图片透明度。

## 好的谢谢，我已经重新调节到适合自己的数值了。
我的问题应该是使用了颜色较浅的背景图片，搭配对比度较强的字体颜色主题，即使Blend Module设置为auto，也不适合再添加模糊度设置了。因为这种情况下，字体与背景的对比度过低，而且背景具有一定的透明度，不利于文本显示。之前的问题，大概是因为透明度误调了QwQ
