### ISSUE TITLE
Linux(Debain,ubunut,centos,fedora...)无法显示图片的权限修改

### ISSUE THREAD

**Issue by cosoc** [AShujiao/vscode-background-cover#28]
如果你在linux下插件正常安装而无法正常显示图片.是文件权限造成的.可以把所属用户改成自己常用的用户.如果多用户可以加写权限,具体那个文件望作者补充.这里是直接把目录给了常用用户

```shell
 chown -R 你的用户名  /usr/share/code

```
该命令应该root执行或者sudo 附魔执行  确切是那个文件应该作者给出建议

**Comment by AShujiao** [comment]
多谢建议，后期版本会增加相应的提示的。

**Comment by kuresaru** [comment]
可以参考vscode源码 在文件权限不足时提示提权保存  当时写出来了这段代码
不过因为当时js/ts水平问题可能这段代码不是太好
https://github.com/shalldie/vscode-background/pull/180

**Comment by ying345** [comment]
感谢大佬，我在linux上图片无法正常显示，原来是权限问题

**Comment by Aipra** [comment]
我的电脑相关信息如下
```
Kernel: 6.0.9-arch1-1 
OS: Arch Linux x86_64
```
要改掉权限的文件是`/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.css`
直接输入下述命令即可
```
sudo chown 你的用户名 /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.css
```

**Comment by satoshinji2992** [comment]
wsl要怎么弄
