### ISSUE TITLE
透明度问题

### ISSUE THREAD

**Issue by w1148202451** [AShujiao/vscode-background-cover#3]
透明度修改无效？
![image](https://user-images.githubusercontent.com/32238419/49431146-b91d2080-f7e7-11e8-8b1f-044f9992c087.png)

**Comment by AShujiao** [comment]
有效的，你设置成0.1试下应该会比现在更暗一些。如果你是觉得最大值图片太暗了，那可能需要我发新版了。因为有些色彩鲜艳的图片透明度设置太高可能会导致看不清界面文字的。

**Comment by emtiantian** [comment]
我也是一样的问题 觉得太暗了~ 期待新版本

**Comment by AShujiao** [comment]
> 我也是一样的问题觉得太暗了〜期待新版本

发布新版了，，更新试下吧。

**Comment by emtiantian** [comment]
感谢 可以了~

**Comment by staugur** [comment]
另请问 @AShujiao ，透明背景的图片无效，是不能使用吗？

**Comment by AShujiao** [comment]
> 另请问@AShujiao，透明背景的图片无效，是不能使用吗？

你是说png格式的背景透明图片吗？这种是可以的使用的

**Comment by staugur** [comment]
> > 另请问@AShujiao，透明背景的图片无效，是不能使用吗？
> 
> 你是说png格式的背景透明图片吗？这种是可以的使用的

是的，可实际是，使用了这种后，恢复成了没有背景的样式（仿佛没有安装插件一般）

**Comment by AShujiao** [comment]
> > > 另请问@AShujiao，透明背景的图片无效，是不能使用吗？
> > 
> > 
> > 你是说PNG格式的背景透明图片吗？这种是可以的使用的
> 
> 是的，可实际是，使用了这种后，恢复成了没有背景的样式（仿佛没有安装插件一般）

但我这边测试了下是可以用的，可能是图片问题吧。或者你改下透明度是不是图片太暗没有看到

**Comment by staugur** [comment]
我试的是网上找的和一些工具转成的透明背景，是有问题的；
刚才ps新建了一张，是可以的；
然而现在我也无法测试了，开了opacity插件，哪种透明都 真的透明了 :joy:
