### ISSUE TITLE
安装该插件后，vscode启动会有一个“启动图片”，这个是by design的么？

### ISSUE THREAD

**Issue by alexya** [AShujiao/vscode-background-cover#32]
安装使用该 插件，设定一张图片后。
每次启动vscode时，都会“一闪而过”先显示一下那张图片，再看到/进入vscode的界面。

这个是by-design的，还是一个bug? 

这个一闪而过的“感觉”不太好......

**Comment by AShujiao** [comment]
是的，之前也有这么反馈的，我也觉得不太好，但目前这种通过修改css样式文件只能这样，等后期我有时间改成js实现时应该就不会出这种问题了。

**Comment by alexya** [comment]
refer: https://github.com/microsoft/vscode/issues/84120
可以关注一下这个issue，微软的vscode team已经准备支持设置background image了。到时候，应该可以使用正式/安全的方法设置。
兄弟及时更新啊！
;-)

**Comment by AShujiao** [comment]
可以可以，还好最近没做大的改动，不然又得重新弄了;-)
