### ISSUE TITLE
opacity设置成0的时候，图片清晰但是文字也看不清了

### ISSUE THREAD

**Issue by GardianT** [AShujiao/vscode-background-cover#39]
能参考这个插件，https://marketplace.visualstudio.com/items?itemName=shalldie.background，加一个background.useFront的配置吗。
这个插件分屏的时候效果比较差，就变成两个独立的图片了。

**Comment by AShujiao** [comment]
实现方式不一样，所以没法加这个配置。。。透明度0.00-1这个范围按合适的调吧。。

**Comment by GardianT** [comment]
顺便问下，我对vscode不太熟，但是我知道的是vscode和atom应该都是基于electron实现的
atom也有一个插件叫 editor-background，这个可以给字体下面增加阴影，使得字体显示更清楚一些

问下这个在这个插件里 可以实现吗。

**Comment by AShujiao** [comment]
刚试了下，的确可以让字体更加清楚，有时间我加上这个功能
