### ISSUE TITLE
图片右边有个黑框请问是什么原因， 我和的插件有冲突吗

### ISSUE THREAD

**Issue by FangyimingLode** [AShujiao/vscode-background-cover#42]
![image](https://user-images.githubusercontent.com/57992882/104995200-dd3c2a00-5a60-11eb-8c8b-a22c2de4b59d.png)

**Comment by AShujiao** [comment]
换张图片试下，如果还有就有可能是插件冲突或者其它问题。。暂时还没遇到过这种问题
