### ISSUE TITLE
Readme.md 中的获取管理员权限应该是使用管理员权限打开VSCode

### ISSUE THREAD

**Issue by got991** [AShujiao/vscode-background-cover#43]
Q:How to get the administrator authority?
Q:怎么获取管理员权限呢？

A:In windows,click right button on the vscode's icon,then check the [run with the administrator authority].
A:在windows环境中，可以右键单击vscode的图标，选择【以管理员身份运行】。
这里的Q应该是“怎么使用管理员权限打开VSCode呢？”

**Comment by AShujiao** [comment]
ok，我改下
