### ISSUE TITLE
更新到 1.54.0 后失效

### ISSUE THREAD

**Issue by zbttl** [AShujiao/vscode-background-cover#44]
回退到 1.53.2 才能生效。

**Comment by crazyair** [comment]
vscode 版本: 1.54.1  失效了

**Comment by AShujiao** [comment]
新版本暂时可以先使用https协议的图片地址，
![image](https://user-images.githubusercontent.com/14969576/110063620-7079b680-7da6-11eb-839c-03c6ffd910ea.png)

**Comment by AShujiao** [comment]
本地文件目前的解决方法为：当图片、或图片目录放到vscode扩展目录下，例如windows：C:\Users\Administrator\.vscode\extensions\。然后重新配置下图片目录

**Comment by crazyair** [comment]
vscode 增加权限了？那应该开放api，等修复，用几天无背景的吧先

**Comment by StRuLLLE** [comment]
追更啦追更啦！1.54.1，作者大大快修复呀

**Comment by FFarewell** [comment]
作者大大加油，最爱这个插件了，赶紧更新呀

**Comment by kuresaru** [comment]
测试发现把图片放到css同目录, css里使用 background-image: url(./xxx.png) 正常

**Comment by yuhenghuang** [comment]
linux下图片要放在user的里的 *~/.vscode/extension/* 下。
在root的vscode启动后改了不会有效果，重新用user开vscode就行了。

**Comment by AShujiao** [comment]
晚上更新噢各位

**Comment by nshusr** [comment]
@AShujiao 新版本会是用什么方法解决呢

**Comment by AShujiao** [comment]
插件已更新

**Comment by AShujiao** [comment]
> @AShujiao 新版本会是用什么方法解决呢

@kuresaru 提交的pr #45 ，把本地文件转base64

**Comment by Iwannnn** [comment]
vscode 打开的时候图片闪一下是正常的情况吗

**Comment by AShujiao** [comment]
> vscode 打开的时候图片闪一下是正常的情况吗

正常
