### ISSUE TITLE
explorer 和 终端背景没法一起改么？

### ISSUE THREAD

**Issue by jmjkx** [AShujiao/vscode-background-cover#47]
如题 
感觉只改代工作区背景 总有点分裂的感觉 
如果终端区域 和 左边区域也可以换背景就好了

**Comment by AShujiao** [comment]
没看懂你的意思，现在不就是一张图片覆盖了所有吗？包含你说的终端和左边区域。。如果你的意思是说这三个区域分别显示单独的图片目前是不行的
