### ISSUE TITLE
Title shows `[unsupported]` after enabling the background

### ISSUE THREAD

**Issue by DriftAsimov** [AShujiao/vscode-background-cover#54]
The extension works perfectly in VS Code but the title shows up like this:

![image](https://user-images.githubusercontent.com/65854695/121837764-13ba6000-ccf4-11eb-9cf2-530512139b80.png)

I have tried restarting and reinstalling the theme which didn't help as well. 

**OS**: Windows 10

**Comment by AShujiao** [comment]
You can search the store to install this extension remove this message: "fix vscode checksums"

**Comment by AShujiao** [comment]
Because there is no official API for the current change background, this information is not removed particularly effectiv

**Comment by DriftAsimov** [comment]
That really helped, although I had it installed previously, applying the checksums again fixed the problem. Thanks!
