### ISSUE TITLE
为什么vscode新窗口打开时，背景图会闪一下

### ISSUE THREAD

**Issue by arsize** [AShujiao/vscode-background-cover#55]
打开新窗口时背景图透明度会失效：
![image](https://user-images.githubusercontent.com/24858265/122522360-7723f500-d048-11eb-9182-3d860b65dae4.png)
大概2秒不到就会恢复正常。

**Comment by AShujiao** [comment]
抱歉，这个问题目前无法解决。刚打开时css还没生效所以会出现短暂的这个情况。。
