### ISSUE TITLE
Error whenever I try to set background

### ISSUE THREAD

**Issue by ayush-py-dev** [AShujiao/vscode-background-cover#56]
I get this error whenever I try to set background...
![shot-2021-06-25_16-24-08](https://user-images.githubusercontent.com/77532758/123415390-cf23a400-d5d2-11eb-8c7a-061d2dcb7ad0.png)

My OS:
Bodhi Linux 6.0

Steps:
> I add a directory and select image
> I press Ctrl+Shift+P
> And I try to refresh it

`Then this error pops up`
![shot-2021-06-25_16-24-08](https://user-images.githubusercontent.com/77532758/123416649-794ffb80-d5d4-11eb-833c-ca954247a772.png)

**Comment by AShujiao** [comment]
Reference: #28 

It may be caused by no permission. You can try to increase the permission
