### ISSUE TITLE
透明度增强

### ISSUE THREAD

**Issue by you-hengh** [AShujiao/vscode-background-cover#57]
如标题所示,
我有一些图片希望透明能`更加透明`一些,期待更新!

![1](https://user-images.githubusercontent.com/34816426/124690258-7de9ad80-df0c-11eb-93a9-b206067b6d7b.jpg)

非常感谢(｡◕◡◕｡)ﾉ

**Comment by AShujiao** [comment]
增加了2个点的透明度，不过目前没法发布版本，上传包被墙了..

**Comment by AShujiao** [comment]
不过你可以通过修改源文件样式来改透明度，c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.css
找到body的样式自己定义

**Comment by you-hengh** [comment]
> 增加了2个点的透明度，不过目前没法发布版本，上传包被墙了..

可否上传至gitee呢?其实透明度交给用户就好,开发者没有必要操心用户的透明度是否适当,这增加了开发者的维护成本,用户自己会调整到一个合适的透明度的,所以建议给用户完全透明的选择,Thanks♪(･ω･)ﾉ

**Comment by AShujiao** [comment]
> > 增加了2个点的透明度，不过目前没法发布版本，上传包被墙了..
> 
> 可否上传至gitee呢?其实透明度交给用户就好,开发者没有必要操心用户的透明度是否适当,这增加了开发者的维护成本,用户自己会调整到一个合适的透明度的,所以建议给用户完全透明的选择,Thanks♪(･ω･)ﾉ
这个图片其实是前景，如果透明度一点也不限制，会出现图片完全覆盖导致vscode菜单及代码完全看不到，出现这种情况就有点糟糕了。。

**Comment by AShujiao** [comment]
https://github.com/AShujiao/vscode-background-cover/releases/tag/2.2.6

到这里下载吧
