### ISSUE TITLE
code server的style覆盖问题

### ISSUE THREAD

**Issue by asuka-mio** [AShujiao/vscode-background-cover#62]
先提个issue罢，之前在code server上试了试这个扩展，发现还是能用的，只不过要改一些东西
首先就是css文件名不一样了
https://github.com/AShujiao/vscode-background-cover/blob/master/src/FileDom.ts#L6
的workbench.desktop.main.css是workbench.web.api.css
另一个问题就是code server有个函数
https://github.com/cdr/code-server/blob/ed1ded51c7fd5a6ff8b92f022220472ff38933bf/src/browser/pages/vscode.ts#L170
就直接导致background那些元素被style覆盖了
临时解决方法就是把安装目录下/out/browser/pages/vscode.browserified.js 第718行的调用
setBodyBackgroundToThemeBackgroundColor(_document, _localStorage);删掉
这两个改了就可以用了
要是有大佬有更好的实现方式那就十分感谢了

**Comment by AShujiao** [comment]
抱歉，最近没上来看。
我觉得还是直接在本地上安装使用吧，没必要在code server上单独装。
这个问题我抽时间看下吧。。
