### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Asthestarsfalll** [AShujiao/vscode-background-cover#63]
刚开始安装的时候有背景图片，过了几天只有打开VScode时会闪出背景图片，然后就没有了

**Comment by Asthestarsfalll** [comment]
似乎是其他插件的影响，已经好了。
但是感觉加了图片之后代码不太清晰，请问如何将图片加在代码的下方

**Comment by AShujiao** [comment]
那只有降低图片透明度了
