### ISSUE TITLE
对于在VSCODE中查看图片会把需要查看的图片透明掉

### ISSUE THREAD

**Issue by sjtuwater** [AShujiao/vscode-background-cover#65]
RT
![image](https://user-images.githubusercontent.com/61745138/134009084-c8a9b3d9-daf2-4c93-92db-76c40517db11.png)
打开图片图片会被透明掉，希望能够改进一下

**Comment by AShujiao** [comment]
这个貌似不太好改，其实插件是将图片做为前景图来实现的，只是做了透明让你感觉他是个背景图。。。
