### ISSUE TITLE
4k显示器窗口最大化底部图片有溢出

### ISSUE THREAD

**Issue by yuanzhel** [AShujiao/vscode-background-cover#72]
![image](https://user-images.githubusercontent.com/50286024/144211258-26849733-594c-49d2-b088-fd07d6902208.png)
非最大化情况下正常显示
![image](https://user-images.githubusercontent.com/50286024/144211322-ab67c69e-7ccf-4ffb-bb6b-323567ba1147.png)
有时窗口化也会出这个问题，需要手动调整一下窗口大小

**Comment by yuanzhel** [comment]
目前的解决办法是只能手动把窗口拉到最大，无法使用最大化按钮

**Comment by AShujiao** [comment]
。。额，这个issue好久了，可能当时忘记回复了，抱歉。这种问题不太好处理。先关闭了。。
