### ISSUE TITLE
我之前安装过，然后图片无法全屏就卸载了，但是图片却没法去掉。

### ISSUE THREAD

**Issue by tomuGo** [AShujiao/vscode-background-cover#75]
然后我现在看可以全屏了，就安装了一下，新图片确实全屏了，但是和以前的图片重叠在一起

**Comment by AShujiao** [comment]
你之前的图片应该是使用这个扩展添加上去的--[backgound](https://marketplace.visualstudio.com/items?itemName=shalldie.background)。
解决方法：你尝试再安装之前的这个扩展把图片禁用\关闭，之后再去卸载
