### ISSUE TITLE
请问您的鼠标移动效果是哪个插件？感谢！

### ISSUE THREAD

**Issue by timenb123** [AShujiao/vscode-background-cover#78]
如题

**Comment by AShujiao** [comment]
https://marketplace.visualstudio.com/items?itemName=manasxx.nest
拿好，还有其它插件可以看下我的主页。。。

**Comment by timenb123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by timenb123** [comment]
感谢
