### ISSUE TITLE
可以只设置窗体半透明, 不设置图片吗?

### ISSUE THREAD

**Issue by echoonly** [AShujiao/vscode-background-cover#80]
如题, 能不能不设置图片, 只把窗体半透明,这样可以透过窗体看到桌面.

**Comment by AShujiao** [comment]
https://marketplace.visualstudio.com/items?itemName=skacekachna.win-opacity
那你可以看下这个扩展。。

**Comment by echoonly** [comment]
@AShujiao  这个扩展只对win平台生效，我在MacOS上试过无效，作者解释说用了win平台的API，他自己没有Mac平台设备，所以没做

**Comment by AShujiao** [comment]
那就没有好的解决办法了。。
