### ISSUE TITLE
VS code 1.67.2 设置背景图片无效

### ISSUE THREAD

**Issue by tianluanchen** [AShujiao/vscode-background-cover#82]
VS code 1.67.2 设置背景图片无效
配置如下，管理员运行也不行，求解决
```json
"backgroundCover.imagePath": "https://ftp.bmp.ovh/imgs/2021/07/5cd647c3993cbf19.jpg",
"backgroundCover.opacity": 0.35,
```
![图片](https://user-images.githubusercontent.com/75252550/170818300-8f46c7b4-730f-48d2-9708-513e826f3b65.png)

**Comment by tianluanchen** [comment]
系统：Windows10

**Comment by AShujiao** [comment]
请使用vscode右下角任务栏的切换背景按钮使用，直接改配置是不会生效的。

**Comment by tianluanchen** [comment]
> 请使用vscode右下角任务栏的切换背景按钮使用，直接改配置是不会生效的。

试了没有用  @AShujiao

**Comment by AShujiao** [comment]
那不应该呀，我和你的一样也是win10。重装下扩展试试吧

**Comment by AShujiao** [comment]
..额，话说我的也是最新版的vscode。。

**Comment by tianluanchen** [comment]
看来没办法解决了，那我就关了
