### ISSUE TITLE
Mac 一直管理员密码错误   这个密码不可能输错

### ISSUE THREAD

**Issue by myy520** [AShujiao/vscode-background-cover#83]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/41657450/173001845-fc98587a-ae89-423f-b88d-95d4207d1de2.png">

**Comment by lauset** [comment]
或许是因为密码中包含特殊字符造成的，尝试打开终端后使用下方命令测试是否能成功执行，将123456替换为管理员密码，/test替换为电脑的某个只读目录

echo "123456" | sudo -S chmod a+rwx "/test"

**Comment by myy520** [comment]
修改了css 权限   现在输入密码没报错   图片还是没加载出来

**Comment by AShujiao** [comment]
![image](https://user-images.githubusercontent.com/14969576/174464740-a1eb8b27-7266-4ba4-9a62-b66903b95209.png)
这里有个类似的问题你可以参考下。。
