### ISSUE TITLE
图片总是不随机

### ISSUE THREAD

**Issue by has-7** [AShujiao/vscode-background-cover#84]
rt

**Comment by AShujiao** [comment]
有没有按下面这个步骤操作：
1、首先确保你添加了图片目录，并且目录里有多张图片
2、开启启动自动更换图片

**Comment by AShujiao** [comment]
自动更换是在启动vscode后扩展激活时触发的，所以也不要刚启动vscode扩展还没激活就重启（关闭）vscode
