### ISSUE TITLE
刚才更新了vscode，然后第一次安装这个插件，发现用不了。

### ISSUE THREAD

**Issue by GDY-BJN** [AShujiao/vscode-background-cover#86]
打开时，图片会闪一下，然后文件背景并没有图片显示。头秃

**Comment by AShujiao** [comment]
是不是透明度没有调整好或者多试下，我这边正常

**Comment by GDY-BJN** [comment]
解决了，之前我用的另外一款background设置了一些参数，后来卸载它后，原始的配置并没有抹除，不仅不显示我原来设置的背景，还把我整个vscode虚化了，我把它重新下回来，开启服务并回复透明度，然后停用，最后卸载才好。现在没任何问题了，还是你的这个插接可玩性高！！！赞
