### ISSUE TITLE
mac下选择背景图，提示输入管理员密码，一直说密码可能错误

### ISSUE THREAD

**Issue by shizhongshiwairen** [AShujiao/vscode-background-cover#87]
EROFS: read-only file system, open '/private/var/folders/qd/f0w8_wfs0yx7f663pqf1pgc80000gn/T/AppTranslocation/E2066CD6-E82A-4ED0-B23B-82FCC2B3C171/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css'

请问是我忽略了什么吗

**Comment by AShujiao** [comment]
@lauset  来解答下，没mac对这块也不清楚

**Comment by lauset** [comment]
可能还是vscode应用内部的样式文件没权限写入的问题，我稍后看一下看看能不能修复一下

**Comment by Nsir15** [comment]
我也遇到了，试了好几次输入密码一直报错

**Comment by huoyou** [comment]
我在mac上也碰到了这个问题，把vscode从download文件夹移入应用程序文件夹后，完美解决

**Comment by MisakaEimi** [comment]
> > 我也遇到了，试了好几次输入密码一直报错
> 
> 当mac上选择图片后出现输入密码的选项，其实际上就是没有权限去操作app内的样式文件
> 
> App内的样式文件信息如下：
> 
> 文件名称：**workbench.desktop.main.css** 文件位置： VS Code 在: /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css VS Code Insiders 的位于：/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css
> 
> 因为我经常输入密码从没有遇到密码报错的情况（除了不是我真的输入错误了），所以我暂时无法判断是因为密码🈶️特殊字符还是用户角色的问题，所以给出以下情况希望可以帮助大家解决
> 
> 1. 根据上面描述的文件位置找到该css文件，查看该文件的阅读权限，如果没有权限那么vscode便会弹出密码框
> 2. 可直接手动修改该文件的阅读权限为`读取和写入`便于解决问题

**Comment by huoyou** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by MisakaEimi** [comment]
手动修改该文件的阅读权限为读取和写入

**Comment by lizhenwei188** [comment]
我的为啥一直不行，权限也改为 777 了

**Comment by huoyou** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by coffeeDanny** [comment]
vscode从download文件夹移入应用程序文件夹,同时也修改了权限，依然不行🙅

**Comment by huoyou** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by MilkyFog** [comment]
我解决了 不用修改那个权限 就是把下载里的vscode拖进启动台 这样复制一份后 将原来下载的vscode删除掉

**Comment by Akashdip-N** [comment]
我无法更改文件“workbench.desktop.main.css”的权限，我正在使用以下命令：-“sudo chmod -R 777 workbench.desktop.main.css”

@AShujiao

**Comment by AShujiao** [comment]
> 我无法更改文件“workbench.desktop.main.css”的权限，我正在使用以下命令：-“sudo chmod -R 777 workbench.desktop.main.css”
> 
> @AShujiao
refer to
"I solved the problem of not changing that permission by dragging the downloaded vscode into the launcher and then making a copy and deleting the original downloaded vscode"

![image](https://github.com/AShujiao/vscode-background-cover/assets/14969576/264e3551-7b9f-4e4c-b4e3-71c9f4e9a0a5)

**Comment by Akashdip-N** [comment]
我不知道如何，但问题已自动修复，谢谢 :)
