### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by yuanweijiaopi** [AShujiao/vscode-background-cover#90]
你好，你的软件做的很好，但是我在使用一些长度比较长的图片的时候（特别是一些长度超过了1000px的图片），那么图片只会显示一半，甚至更小，可以在下一个版本中加一个缩放么，感谢。

**Comment by AShujiao** [comment]
因为要保证图片不变形的情况下铺满整个vscode，如果尺寸特别特殊还要完全展示出来，那应该会无法铺满整个vscode了
