### ISSUE TITLE
opacity

### ISSUE THREAD

**Issue by howllow-willow** [AShujiao/vscode-background-cover#92]
how to improve background image opacity

**Comment by AShujiao** [comment]
The current transparency value does not meet your requirements? If the transparency is too high, the text on the interface will not be visible, so there is a limit to the maximum value.
Can't find how to adjust transparency? Then you can look at "redeme".
by:translate.google.cn

**Comment by StudentWeis** [comment]
You can't set it manually, you can only click the icon in the lower right corner and select.
