### ISSUE TITLE
卸载后的自动清理没有正常运行

### ISSUE THREAD

**Issue by shalldie** [AShujiao/vscode-background-cover#97]
我是想过来参考 uninstall 代码发现的问题 😂😂

2个方面：

1. `process.cwd`，并不是 vscode 安装目录。
    -  我的想法是在设置图片阶段，就把安装路径写入硬盘，，，丑了点，但有用
 
2. MacOS，一般情况下，hook 执行不了。
    - 进程并不会完全关闭(需要 `command + q`)。 
    - `vscode:uninstall` 需要在所有进程关闭后，再次打开vscode才会执行。

**Comment by AShujiao** [comment]
难道升级后又改机制了，windows下之前我测试的是没问题的，卸载后需要关闭再打开才会执行是没问题的，mac下我还没有试过。。

**Comment by shalldie** [comment]
我看了下，这里是fork了一下直接执行，没有设置 cwd

https://github.com/microsoft/vscode/blob/0b8e94c15a4b119e26af1c1433392f78ec5aa256/src/vs/platform/extensionManagement/node/extensionLifecycle.ts#L92-L97

路径也是拼接起来的。

https://github.com/microsoft/vscode/blob/0b8e94c15a4b119e26af1c1433392f78ec5aa256/src/vs/platform/extensionManagement/node/extensionLifecycle.ts#L40-L51

**Comment by AShujiao** [comment]
..大佬你这源码都看起来了。我表示看不懂。。。我刚试了下windows下时没问题的，mac下的等你弄好我看看
![image](https://user-images.githubusercontent.com/14969576/201009185-f7317126-bce7-473a-8a99-f48834aa0576.png)

**Comment by KurumiRin** [comment]
系统版本为 macOS Ventura `13.1 Beta版(22C5050e)`
目前是卸载或禁用插件再重启均无法清理背景图片
`background-cover`插件版本为` v2.3.0`

**Comment by AShujiao** [comment]
> macos下确实无法执行自动清理，目前背景图无法正常去除了。有修复的打算吗？

不太好处理，没macos无法调试😅😅
