### ISSUE TITLE
window remote-ssh  ubuntu  could not open the picture of on the ubuntu

### ISSUE THREAD

**Issue by fun1998** [AShujiao/vscode-background-cover#98]
I develop project in ubuntu  using remote-ssh . I find it could not open  the picture on it . how can I solution this problem ? thank you for anyone know this .
window remote-ssh 不能打开ubuntu上的图片，有谁知道解决办法吗？

**Comment by AShujiao** [comment]
linux基本是权限问题，比较麻烦 ，建议使用windows端图片，这样即使使用wsl、ssh也是通用展示图片的
