### ISSUE TITLE
设置图片重启后vscode无法正常显示

### ISSUE THREAD

**Issue by lengyibai** [AShujiao/vscode-background-cover#99]
![image](https://user-images.githubusercontent.com/74140255/206990030-753cbd82-757c-441e-949f-d10fe830f7bc.png)
版本1.73以上

**Comment by AShujiao** [comment]
多试几次也一直这样吗？如果是的可能是css文件写入异常了，请尝试手动打开该文件（C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css），将扩展写入的内容删除或者截图发我下文件内容

**Comment by lengyibai** [comment]
图片被转成base64了，尺寸过大
		/*ext-backgroundCover-start*/
		/*ext.backgroundCover.ver.2.3.0*/
		body{
			background-size: cover;
			background-repeat: no-repeat;
			background-position: center;
			opacity:0.95;
		}
		/*ext-backgroundCover-end*/

**Comment by lengyibai** [comment]
图片被转成base64了，尺寸过大
![image](https://user-images.githubusercontent.com/74140255/206992620-52835786-4d68-435f-9976-a816d566c489.png)

/ext-backgroundCover-start/
/ext.backgroundCover.ver.2.3.0/
body{
background-size: cover;
background-repeat: no-repeat;
background-position: center;
opacity:0.95;
}
/ext-backgroundCover-end/

**Comment by lengyibai** [comment]
找到原因了，是由于vscode-live2d扩展导致的，因为此插件也需要管理员身份运行vscode才能运行，所以在设置背景图后重启，vscode-live2d也跟着启动了
